// Code generated by Slice Machine. DO NOT EDIT.

import Collapsible from './Collapsible';
import Content from './Content';
import Img from './Img';
import Square from './Square';
import Video from './Video';

export {
	Collapsible,
	Content,
	Img,
	Square,
	Video,
};

export const components = {
	collapsible: Collapsible,
	content: Content,
	img: Img,
	square: Square,
	video: Video,
};
