// Code generated by Slice Machine. DO NOT EDIT.

import Content from './Content';
import Square from './Square';

export {
	Content,
	Square,
};

export const components = {
	content: Content,
	square: Square,
};
