// Code generated by Slice Machine. DO NOT EDIT.

import Content from './Content';
import PageContent from './PageContent';
import Square from './Square';

export {
	Content,
	PageContent,
	Square,
};

export const components = {
	content: Content,
	page_content: PageContent,
	square: Square,
};
